nginx:                         
  image: nginx                 
  restart: always
  environment:                 
    - VIRTUAL_HOST=theminingking.com
    - LETSENCRYPT_HOST=theminingking.com
    - LETSENCRYPT_EMAIL=daniel@capitolhill.ca
  volumes:                     
    - ./:/usr/share/nginx/html 
